name: FirstWorkflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print_hi_bye
        run: |
            echo "Greetings"
            echo "Okay, bye!"
